development:
  adapter: postgresql
  database: sample_development
  username:
  password:
  host: localhost
  pool: 5

test: &test
  adapter: postgresql
  database: sample_test
  username:
  password:
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: sample_production
  username:
  password: 
  host: localhost
cucumber:
  <<: *test